spring.application.name=LoanApplicationManagementSystem


spring.datasource.url=jdbc:postgresql://localhost:5432/abesdb2
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=Rish@1810
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8080
#springdoc.swagger-ui.path=/swagger-ui.html